version: '3'
services:
    flask:
        container_name: server-josmas-flask
        build:
            context: .
            dockerfile: docker/Dockerfile.python
        restart: always
        environment:
            FLASK_APP: app
            FLASK_ENV: development
            FLASK_RUN_PORT: 8000
            DB_DATABASE: josmar_db
            DB_USERNAME: flask_user
            DB_PASSWORD: flask_db_password
            DB_HOSTNAME: "0.0.0.0"
            DB_PORT: 5432
        volumes:
            - ./code:/code/
        ports:
            - "8000:8000"

    postgres:
        image: postgres:latest
        restart: always
        container_name: server-josmas-db
        environment:
            POSTGRES_DB: josmar_db
            POSTGRES_USER: flask_user
            POSTGRES_PASSWORD: flask_db_password
        volumes:
            # - /var/lib/postgres
            - ./dbscripts:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"

    adminer:
        image: adminer
        container_name: server-josmas-adminer
        restart: always
        ports:
            - "8080:8080"
